dataset:
  name: "raven"
  path: "/home/wkosiuk/ARC/RAVEN/data"  # Root with config subfolders and embedding.npy

model:
  name: "raven_resnet18"
  pretrained_path: null
  losses:
    - name: "raven_cross_entropy"
      weight: 1.0
  scaler:
    name: "RavenEmbeddingStaticScaler"
    args:
      n_transforms: 4       # number of replicas to generate
      hidden_dim: 300
      dropout: 0.1
  aggregator:
    name: "RavenMeanAggregator"
    args:
      aggregate_dim: 1

training:
  experiment_name: "raven_resnet18_scaler_partial_v1"
  device: "cuda:0"
  batch_size: 16
  learning_rate: 0.0001
  epochs: 1
  seed: 42
  num_workers: 4
  eval_interval: 200
  # scaler_regime: "partial"  # train only scaler+aggregator parameters
  scaler_regime: "full"  # train all parameters
  training_metrics: ["accuracy"]
  validation_metrics: ["accuracy"]
