training:
  batch_size: 128
  num_workers: 4
  learning_rate: 0.001
  epochs: 1
  eval_interval: 12900
  device: "cpu"
  experiment_name: "sudoku-nf-mean-aggregator-partial"
  training_metrics: ["accuracy", "accuracy_sudoku"]
  validation_metrics: ["accuracy", "accuracy_sudoku"]
  seed: 42
  scaler_regime: "partial"

dataset:
  name: "sudoku"
  path: "./data/sudoku"

model:
  name: "SudokuCNN"
  losses: [{"name": "sudoku_loss", "weight": 1.0}]
  scaler:
    name: "SudokuNormalizingFlowScaler"
    args:
      n_coupling_layers: 2
      hidden_dim: 32
      n_reps: 2
      n_coupling_net_layers: 2
  aggregator:
    name: "MeanAggregator"
    args:
      aggregate_dim: 1