training:
  experiment_name: "sudoku-baseline"
  # Hardware parameters
  num_workers: 4 # Number of workers for dataloader
  device: "cuda:0" # Device to use for training
  # Training parameters
  batch_size: 1024
  learning_rate: 0.005
  epochs: 50
  # scheduler:
  #   name: "linear"
  #   args:
  #     start_factor: 0.1
  #     end_factor: 1.0
  #     total_iters: 3000
  # Validation parameters
  eval_interval: 500
  training_metrics: ["accuracy", "accuracy_unknown_cells"]
  validation_metrics: ["accuracy", "accuracy_unknown_cells"]
  checkpoint_metric:
    name: "accuracy_unknown_cells"
    mode: "max"
  # Seed for reproducibility
  seed: 42
  
dataset:
  name: "sudoku"
  path: "/var/scratch/dchernia/sudoku"

model:
  name: "SudokuCNN"
  losses: [{"name": "cross_entropy", "weight": 1.0}]
  args:
    dropout: 0.2