training:
  experiment_name: "sudoku-deep-mean23-midlayers=3-dropout=0.5-batchsize=256-lr=0.001-short-decoder-relu"
  num_workers: 4
  device: "cuda:0"
  batch_size: 256
  learning_rate: 0.001
  epochs: 1
  eval_interval: 500
  training_metrics: ["accuracy", "accuracy_unknown_cells"]
  validation_metrics: ["accuracy", "accuracy_unknown_cells"]
  checkpoint_metric:
    name: "accuracy_unknown_cells"
    mode: "max"
  seed: 42
  logger: "sudoku_logger"
  max_samples_to_log: 16

dataset:
  name: "sudoku"
  path: "./data/sudoku"
  args:
    filter_train: false

model:
  name: "SudokuCNN"
  losses: [{"name": "cross_entropy_loss", "weight": 1.0}]
  args:
    dropout: 0.5
    n_mid_layers: 3
  pretrained_path: "sudoku/sudoku_baseline/best_model.pt"
  pretrained_from_hf: "danchern/noisescaling"
  scaler:
    name: "SudokuStaticScaler"
    inj_point: 3         
    args:
      n_transforms: 2
      layer_type: "conv"
      dim: 256            
  aggregator:
    name: "MeanAggregator"
    inj_point: 5       
    args:
      aggregate_dim: 1     